cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart_detail'),
    path('add-to-cart/<slug:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-quantity/<slug:slug>/', ChangeQuantityInCart.as_view(), name='change_quantity')
]

orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('cancel-order/<int:id>/', CancelOrderView.as_view(), name='cancel_order')
]

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path(r'products/<slug:category>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path(r'products/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path(r'search/', SearchView.as_view(), name='search')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('cart.urls')),
    path('', include('users.urls')),
    path('', include('orders.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.utils import timezone
from products.models import Product


class Order(models.Model):

    STATUS_CHOICES = (
        ('new_order', 'Новый заказ'),
        ('order_in_process', 'Заказ в обработке'),
        ('order_ready', 'Заказ готов'),
        ('order_done', 'Заказ выполнен')
    )

    TYPE_CHOICES = (
        ('delivery', 'Доставка'),
        ('pickup', 'Самовывоз')
    )

    PAYMENT_CHOICES = (
        ('online', 'Онлайн оплата'),
        ('cash', 'Оплата наличными')
    )

    user = models.ForeignKey('users.User', verbose_name='Покупатель', on_delete=models.CASCADE, related_name='related_orders', blank=True)
    address = models.CharField(verbose_name='Адрес', max_length=255, blank=True)
    phone = models.CharField(verbose_name='Номер телефона', max_length=17, blank=True)
    first_name = models.CharField(verbose_name="Имя покупателя", max_length=40, blank=True)
    last_name = models.CharField(verbose_name="Фамилия покупателя", max_length=40, blank=True)
    created = models.DateField(verbose_name='Дата создания', auto_now=True)
    ready_date = models.DateField(verbose_name='Дата готовности', default=timezone.now)
    ready_time = models.TimeField(verbose_name='Время готовности', default=timezone.now)
    status = models.CharField(verbose_name="Статус заказа", max_length=20, choices=STATUS_CHOICES, default='new_order')
    orderType = models.CharField(verbose_name="Тип заказа", max_length=20, choices=TYPE_CHOICES, default='delivery')
    payment = models.CharField(verbose_name="Тип оплаты", max_length=20, choices=PAYMENT_CHOICES, default='online')
    comment = models.CharField(verbose_name="Комментарий к заказу", max_length=255, blank=True)
    products = models.ManyToManyField('OrderItem', verbose_name="Продукты", blank=True,
                                      related_name="related_products")

    def __str__(self):
        return f"Заказ пользователя {self.user.email}"


class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Заказ', on_delete=models.CASCADE, related_name='related_order')
    product = models.ForeignKey(Product, verbose_name="Продукт", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="Количество", default=1)
    overall_price = models.DecimalField(verbose_name="Цена товара", max_digits=9, decimal_places=2)

    def save(self, *args, **kwargs):
        self.overall_price = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Пункт заказа пользователя {self.order.user.email}"

templates/profile/user_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'products:home' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Профиль</li>
        </ol>
    </nav>
    <h3 class="mt-3">Профиль пользователя</h3>
    <div class="row mt-3">
        <div class="col-sm-3">Email:</div>
        <div class="col-md-8">{{ user_profile.user.email }}</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-3">Имя:</div>
        <div class="col-md-8">{{ user_profile.first_name }}</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-3">Фамилия:</div>
        <div class="col-md-8">{{ user_profile.last_name }}</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-3">Адрес:</div>
        <div class="col-md-8">{{ user_profile.address }}</div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-3">Номер телефона:</div>
        <div class="col-md-8">{{ user_profile.phone_number }}</div>
    </div>
    {% if user_profile.orders.count %}
    <h3 class="mt-3">Заказы пользователя:</h3>
    {% for order in user_profile.orders.all %}
    <div class="card mt-3 mb-3">
        <div class="card-body">
            <h5 class="card-title">Заказ</h5>
            <p class="card-text">Статус: {{ order.get_status_display }}</p>
            <p class="card-text">Тип: {{ order.get_orderType_display }}</p>
            <p class="card-text">Тип оплаты: {{ order.get_payment_display }}</p>
            <p class="card-text">Дата готовности: {{ order.ready_date }}</p>
            <p class="card-text">Время готовности: {{ order.ready_time }}</p>
            <p class="card-text">Адрес доставки: {{ order.address }}</p>
            <p class="card-text">Телефон: {{ order.phone }}</p>
            <h6 class="card-text">Продукты:</h6>
            <ul class="list-group">
                {% for order_item in order.products.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ order_item.product.name }}
                    <span class="badge alert-success">{{ order_item.quantity }}</span>
                </li>
                {% endfor %}
            </ul>
            {% if order.status == 'new_order' %}
            <a href="{% url 'orders:cancel_order' id=order.id %}">
                <button class="btn btn-danger mt-3">Отменить заказ</button>
            </a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h3 class="mt-3">Заказов нет</h3>
    {% endif %}
</div>
{%endblock %}