cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart_detail'),
    path('add-to-cart/<slug:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-quantity/<slug:slug>/', ChangeQuantityInCart.as_view(), name='change_quantity')
]

orders/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('cancel-order/<int:id>/', CancelOrderView.as_view(), name='cancel_order')
]

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path(r'products/<slug:category>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path(r'products/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path(r'search/', SearchView.as_view(), name='search')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('cart.urls')),
    path('', include('users.urls')),
    path('', include('orders.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from products.models import Product
from users.models import User


class Cart(models.Model):
    user = models.ForeignKey(User, verbose_name="Корзина", on_delete=models.CASCADE)
    products = models.ManyToManyField('CartProduct', verbose_name="Продукты", blank=True,
                                      related_name="related_products")
    products_amount = models.PositiveIntegerField(verbose_name="Количество продуктов", default=0)
    overall_price = models.DecimalField(verbose_name="Цена корзины", default=0, max_digits=9, decimal_places=2)
    is_in_order_process = models.BooleanField(verbose_name="В процессе заказа", default=False)
    is_for_anonymous_user = models.BooleanField(verbose_name="Для анонимного пользователя", default=False)

    def __str__(self):
        return f"Корзина пользователя {self.user.email}"


class CartProduct(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, verbose_name="Корзина", on_delete=models.CASCADE, related_name="related_cart")
    product = models.ForeignKey(Product, verbose_name="Продукт", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="Количество", default=1)
    overall_price = models.DecimalField(verbose_name="Цена товара", max_digits=9, decimal_places=2)

    def __str__(self):
        return f"В корзине продукт {self.product.name}"

    def save(self, *args, **kwargs):
        self.overall_price = self.product.price * self.quantity
        super().save(*args, **kwargs)

cart/views.py
from django.shortcuts import render
from django.views.generic.detail import View
from .async_requests import *
import asyncio
from .utilities import update_cart
from .models import Cart, CartProduct
from products.models import Product
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
import logging

logger = logging.getLogger(__name__)


class CartView(LoginRequiredMixin, View):

    def get(self, request):
        cart_obj = asyncio.run(get_cart(request.user))
        logger.info(f"Loading cart view for user {request.user}")
        return render(request, 'cart/cart_detail.html', {'cart': cart_obj})


class AddToCartView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        cart = asyncio.run(get_cart(request.user))
        product = asyncio.run(get_product(kwargs.get('slug')))
        cart_product, created = asyncio.run(get_or_create_cart_product(cart, product))
        if created:
            cart.products.add(cart_product)
        else:
            cart_product.quantity += 1
            cart_product.save()
        update_cart(cart)
        logger.info(f"Added product {product.id} to cart for user {request.user}")
        return HttpResponseRedirect('/cart/')


class DeleteFromCartView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        cart = asyncio.run(get_cart(request.user))
        product = asyncio.run(get_product(kwargs.get('slug')))
        cart_product = asyncio.run(get_cart_product(cart, product))
        cart.products.remove(cart_product)
        cart_product.delete()
        update_cart(cart)
        logger.info(f"Deleted cart product {cart_product.id} from cart for user {request.user}")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ChangeQuantityInCart(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        cart = asyncio.run(get_cart(request.user))
        product = asyncio.run(get_product(kwargs.get('slug')))
        cart_product = asyncio.run(get_cart_product(cart, product))
        quantity = int(request.POST.get('quantity'))
        cart_product.quantity = quantity
        cart_product.save()
        update_cart(cart)
        logger.info(f"Changed quantity for cart product {cart_product.id} for user {request.user}")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'products:home' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Корзина</li>
        </ol>
    </nav>
    {% if cart.products.count %}
    <div class="row">
        <div class="col-md-8">
            <h3>Моя корзина</h3>
            <table id="cart" class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th scope="col" style="width:30%">Изображение</th>
                    <th scope="col" style="width:20%">Название</th>
                    <th scope="col" style="width:10%">Количество</th>
                    <th scope="col" style="width:15%">Цена</th>
                    <th scope="col" style="width:15%">Общая Цена</th>
                    <th scope="col" style="width:10%">Действие</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_product in cart.products.all %}
                <tr>
                    <th scope="row" class="w-10"><img src="{{ cart_product.product.image.url }}" class="img-fluid"></th>
                    <td>{{ cart_product.product.name }}</td>
                    <td>
                        <form action="{% url 'change_quantity' slug=cart_product.product.slug %}" method="POST">
                            {% csrf_token %}
                            <input id="productNumber" type="number" class="form-control" style="width:85px;" min="1"
                                   max="100" name="quantity" value="{{ cart_product.quantity }}" onchange="this.form.submit()">
                        </form>
                    </td>
                    <td>{{ cart_product.product.price }} BYN</td>
                    <td>{{ cart_product.overall_price }} BYN</td>
                    <td><a href="{% url 'delete_from_cart' slug=cart_product.product.slug %}">
                        <button class="btn btn-danger">Удалить из корзины</button>
                    </a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-4">
            <h3>Информация о корзине: </h3>
            <h4>Количество товаров в корзине: {{ cart.products_amount }}</h4>
            <h4>Общая цена: {{ cart.overall_price }}</h4>
            <a href="{% url 'orders:make_order' %}"><button class="btn btn-success">Оформить заказ</button></a>
        </div>
    </div>
    {% else %}
    <h3>Корзина пуста</h3>
    {% endif %}
</div>
{% endblock %}