cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart_detail'),
    path('add-to-cart/<slug:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('delete-from-cart/<slug:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-quantity/<slug:slug>/', ChangeQuantityInCart.as_view(), name='change_quantity')
]

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path(r'products/<slug:category>/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path(r'products/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path(r'search/', SearchView.as_view(), name='search')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('cart.urls')),
    path('', include('users.urls')),
    path('', include('orders.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
    <title>{% block title %}E-shop{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light navbar-light">
    <a class="navbar-brand" href="{% url 'products:home' %}">E-Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <div class="search-bar">
            <form method="post" action="{% url 'products:search' %}">
                <div class="input-group">
                    {% csrf_token %}
                    <input name="search" id="search" class="form-control mr-sm-2" type="search"
                           placeholder="Поиск" aria-label="Search" style="">
                    <div class="input-group-append">
                        <button class="btn btn-outline-dark pr-2" type="submit">Найти</button>
                    </div>
                </div>
            </form>
        </div>
        <ul class="navbar-nav">
            <li class="dropdown">
                <a class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Категории
                </a>
                <ul class="dropdown-menu">
                    {% for category in categories %}
                    <li><a class="dropdown-item" href='{{ category.get_absolute_url }}'>{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart_detail' %}">Корзина</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_profile' %}">Профиль</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Выйти из аккаунта</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Войти</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<main>
    {% block content %}
    {% endblock %}
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</body>
<footer class="bg-light text-center">
    <div class="text-center p-3">
        2021 E-shop
    </div>
</footer>
</html>